name: artifact

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: cargo build --release --verbose

      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v3
        with:
          name: artifact
          path: target/release
          retention-days: 20